import {
  generatedDir,
  generatedFileName,
  generatedSiblingImport,
  modelKeyToClassName,
  pathParamToDecoratorName,
  resolveApplicationKey,
} from "../../builders/naming";
import {
  normalizeControllerPath,
  operationMethodName,
  resolveType,
  resourceKeyToControllerClassName,
} from "../../builders/type-mapping";
import { GeneratedFilePayload, InvocationForm } from "../../types";

function fileHeader(namespace: string): string {
  return `/**\n * Generated by Forsyte Generator from ${namespace}\n * Do not edit — regenerate from apibuilder.\n */\n`;
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function httpDecorator(method: string, path?: string): string {
  const nestMethod = capitalize(method.toLowerCase());
  const routePath = path?.replace(/^\//, "") ?? "";
  return routePath ? `@${nestMethod}("${routePath}")` : `@${nestMethod}()`;
}

const HTTP_STATUS_ENUM: Record<string, string> = {
  "200": "OK",
  "201": "CREATED",
  "202": "ACCEPTED",
  "204": "NO_CONTENT",
};

function defaultStatusForMethod(method: string): number {
  if (method.toLowerCase() === "post") {
    return 201;
  }
  return 200;
}

function pickSuccessStatus(responses: Record<string, { type: string }>): string {
  for (const status of ["200", "201", "202", "204"]) {
    if (responses[status]) {
      return status;
    }
  }
  const twoxx = Object.keys(responses)
    .filter((status) => {
      const code = Number.parseInt(status, 10);
      return code >= 200 && code < 300;
    })
    .sort((a, b) => Number.parseInt(a, 10) - Number.parseInt(b, 10));
  return twoxx[0] ?? "200";
}

function httpCodeDecorator(method: string, successStatus: string): string | null {
  const status = Number.parseInt(successStatus, 10);
  if (status === defaultStatusForMethod(method)) {
    return null;
  }
  const enumName = HTTP_STATUS_ENUM[successStatus];
  if (enumName) {
    return `@HttpCode(HttpStatus.${enumName})`;
  }
  return `@HttpCode(${status})`;
}

function apiSuccessDecorator(successStatus: string, tsType: string): string {
  if (successStatus === "204" || tsType === "void") {
    return "@ApiNoContentResponse()";
  }

  const isArray = tsType.endsWith("[]");
  const baseType = isArray ? tsType.slice(0, -2) : tsType;
  const arraySuffix = isArray ? ", isArray: true" : "";

  if (successStatus === "201") {
    return `@ApiCreatedResponse({ type: ${baseType}${arraySuffix} })`;
  }
  return `@ApiOkResponse({ type: ${baseType}${arraySuffix} })`;
}

function apiErrorDecorator(status: string, tsType?: string): string | null {
  switch (status) {
    case "401":
      return "@ApiUnauthorizedResponse()";
    case "404":
      return "@ApiNotFoundResponse()";
    case "409":
      return "@ApiConflictResponse()";
    case "422":
      return tsType ? `@ApiUnprocessableEntityResponse({ type: ${tsType} })` : "@ApiUnprocessableEntityResponse()";
    default:
      return `@ApiResponse({ status: ${status} })`;
  }
}

function addLocalDtoImports(type: string, form: InvocationForm, localDtoImports: Set<string>): void {
  const arrayMatch = /^\[(.+)\]$/.exec(type);
  if (arrayMatch) {
    addLocalDtoImports(arrayMatch[1], form, localDtoImports);
    return;
  }
  if (form.service.models?.[type]) {
    localDtoImports.add(modelKeyToClassName(type));
  }
}

function emitResourceController(
  resourceKey: string,
  form: InvocationForm,
  localDtoImports: Set<string>,
  externalImports: Set<string>,
): string {
  const resource = form.service.resources?.[resourceKey];
  if (!resource) {
    return "";
  }

  const controllerClass = resourceKeyToControllerClassName(resourceKey, resource.path);
  const controllerPath = normalizeControllerPath(resource.path);
  const blocks: string[] = [];

  for (const operation of resource.operations) {
    const methodName = operationMethodName(operation.method, operation.path);
    const successStatus = pickSuccessStatus(operation.responses);
    const successResponse = operation.responses[successStatus];
    const { tsType: successType, imports: successImports } = resolveType(
      successResponse?.type ?? "unit",
      form.service,
      form.imported_services ?? [],
    );
    successImports.forEach((line) => externalImports.add(line));
    addLocalDtoImports(successResponse?.type ?? "unit", form, localDtoImports);

    const returnType = successType === "void" ? "void" : successType;
    const promiseReturn = `Promise<${returnType}>`;

    const hookParams: string[] = [];
    const wireParams: string[] = [];
    const wireDecorators: string[] = [httpDecorator(operation.method, operation.path)];
    const callArgs: string[] = [];

    for (const parameter of operation.parameters ?? []) {
      const camel = pathParamToDecoratorName(parameter.name);
      const tsType = parameter.type === "integer" ? "number" : "string";
      const pathPattern = `:${parameter.name}`;
      const inPath = `${resource.path}/`.includes(pathPattern) || (operation.path ?? "").includes(pathPattern);

      if (inPath) {
        wireDecorators.push(`@ApiParam({ name: "${camel}" })`);
        wireParams.push(`@Param("${camel}") ${camel}: ${tsType}`);
      } else {
        wireDecorators.push(`@ApiQuery({ name: "${camel}", required: ${parameter.required === true} })`);
        wireParams.push(`@Query("${camel}") ${camel}${parameter.required === false ? "?" : ""}: ${tsType}`);
      }
      hookParams.push(`${camel}${parameter.required === false ? "?" : ""}: ${tsType}`);
      callArgs.push(camel);
    }

    if (operation.body) {
      const bodyClass = modelKeyToClassName(operation.body.type);
      localDtoImports.add(bodyClass);
      wireParams.push(`@Body() body: ${bodyClass}`);
      hookParams.push(`body: ${bodyClass}`);
      callArgs.push("body");
    }

    const swaggerDecorators: string[] = [
      apiSuccessDecorator(successStatus, returnType),
      ...Object.entries(operation.responses)
        .filter(([status]) => status !== successStatus)
        .map(([status, response]) => {
          if (response.type === "unit") {
            return apiErrorDecorator(status);
          }
          const { tsType, imports } = resolveType(response.type, form.service, form.imported_services ?? []);
          imports.forEach((line) => externalImports.add(line));
          addLocalDtoImports(response.type, form, localDtoImports);
          return apiErrorDecorator(status, tsType);
        })
        .filter((decorator): decorator is string => decorator !== null),
    ];

    const httpCode = httpCodeDecorator(operation.method, successStatus);
    if (httpCode) {
      swaggerDecorators.unshift(httpCode);
    }

    blocks.push(`  @ApiOperation({ summary: "${operation.description ?? methodName}" })
  ${swaggerDecorators.join("\n  ")}
  ${wireDecorators.join("\n  ")}
  @UsePipes(new ValidationPipe({ whitelist: true, transform: true }))
  async ${methodName}(
    ${wireParams.join(",\n    ")}
  ): ${promiseReturn} {
    return this.${methodName}Hook(${callArgs.join(", ")});
  }

  abstract ${methodName}Hook(${hookParams.join(", ")}): ${promiseReturn};`);
  }

  const decoratorPath = controllerPath ? `'${controllerPath}'` : "''";
  return `@ApiTags("${controllerClass}")
@Controller(${decoratorPath})
export abstract class ${controllerClass} {
${blocks.join("\n\n")}
}`;
}

export async function generateNestJsControllers(form: InvocationForm): Promise<GeneratedFilePayload[]> {
  const resources = form.service.resources ?? {};
  const resourceKeys = Object.keys(resources);
  if (resourceKeys.length === 0) {
    return [];
  }

  const applicationKey = resolveApplicationKey(form.service);
  const dir = generatedDir(applicationKey);
  const localDtoImports = new Set<string>();
  const externalImports = new Set<string>();

  const resourceBlocks = resourceKeys.map((key) =>
    emitResourceController(key, form, localDtoImports, externalImports),
  );

  const enumImports = Object.keys(form.service.enums ?? {}).map((enumKey) => {
    const pascal = enumKey
      .split("_")
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join("");
    return pascal;
  });

  const importBlock = [
    'import { Body, Controller, Delete, Get, HttpCode, HttpStatus, Param, Post, Put, Query, UsePipes, ValidationPipe } from "@nestjs/common";',
    'import { ApiConflictResponse, ApiCreatedResponse, ApiNoContentResponse, ApiNotFoundResponse, ApiOkResponse, ApiOperation, ApiParam, ApiQuery, ApiResponse, ApiTags, ApiUnauthorizedResponse, ApiUnprocessableEntityResponse } from "@nestjs/swagger";',
    localDtoImports.size > 0
      ? `import { ${Array.from(localDtoImports).sort().join(", ")} } from "${generatedSiblingImport(applicationKey, "dtos")}";`
      : "",
    enumImports.length > 0
      ? `import { ${enumImports.join(", ")} } from "${generatedSiblingImport(applicationKey, "enums")}";`
      : "",
    ...Array.from(externalImports).sort(),
  ]
    .filter(Boolean)
    .join("\n");

  const contents = `${fileHeader(form.service.namespace)}${importBlock}\n\n${resourceBlocks.join("\n\n")}`;

  return [
    {
      name: generatedFileName(applicationKey, "controllers"),
      dir,
      contents,
    },
  ];
}
