import {
  enumKeyToClassName,
  generatedDir,
  generatedFileName,
  generatedSiblingImport,
  modelKeyToClassName,
  resolveApplicationKey,
  snakeToCamel,
} from "../../builders/naming";
import { resolveType } from "../../builders/type-mapping";
import { GeneratedFilePayload, InvocationForm } from "../../types";

function fileHeader(namespace: string): string {
  return `/**\n * Generated by Forsyte Generator from ${namespace}\n * Do not edit — regenerate from apibuilder.\n */\n`;
}

function validatorForPrimitive(type: string, required: boolean): string[] {
  const decorators: string[] = [];
  if (!required) {
    decorators.push("@IsOptional()");
  }

  switch (type) {
    case "string":
    case "uuid":
    case "date-iso8601":
    case "date-time-iso8601":
      decorators.push("@IsString()");
      break;
    case "integer":
    case "long":
    case "double":
    case "decimal":
      decorators.push("@IsNumber()");
      break;
    case "boolean":
      decorators.push("@IsBoolean()");
      break;
    default:
      break;
  }

  return decorators;
}

function isFormModel(modelKey: string): boolean {
  return modelKey.endsWith("_form");
}

function emitEnum(enumKey: string, values: Array<{ name: string }>): string {
  const className = enumKeyToClassName(enumKey);
  const members = values.map((v) => `  ${toEnumMember(v.name)} = "${v.name}",`).join("\n");
  return `export enum ${className} {\n${members}\n}\n`;
}

function toEnumMember(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "_").toUpperCase();
}

function emitModelClass(
  modelKey: string,
  form: InvocationForm,
): { code: string; imports: Set<string> } {
  const model = form.service.models?.[modelKey];
  if (!model) {
    return { code: "", imports: new Set() };
  }

  const className = modelKeyToClassName(modelKey);
  const importedServices = form.imported_services ?? [];
  const allImports = new Set<string>();
  const lines: string[] = [];

  for (const field of model.fields) {
    const propertyName = snakeToCamel(field.name);
    const { tsType, imports } = resolveType(field.type, form.service, importedServices);
    imports.forEach((i) => allImports.add(i));

    const optional = field.required === false;
    const nullableSuffix = optional && field.type !== "boolean" ? " | null" : "";
    const propertyType = optional ? `${tsType}${nullableSuffix}` : tsType;
    const propertyMarker = optional ? "?" : "!";

    if (optional) {
      lines.push("  @ApiPropertyOptional()");
    } else {
      lines.push("  @ApiProperty()");
      if (field.type === "string") {
        lines.push("  @IsNotEmpty()");
        lines.push("  @MinLength(1)");
      }
    }
    lines.push("  @Expose()");
    validatorForPrimitive(field.type, !optional).forEach((d) => lines.push(`  ${d}`));
    lines.push(`  ${propertyName}${propertyMarker}: ${propertyType};`);
    lines.push("");
  }

  const exposeImport = isFormModel(modelKey) ? "" : "";
  void exposeImport;

  const code = `export class ${className} {\n${lines.join("\n")}}\n`;
  return { code, imports: allImports };
}

function buildEnumsFile(form: InvocationForm, applicationKey: string, dir: string): GeneratedFilePayload | null {
  const enums = form.service.enums ?? {};
  const keys = Object.keys(enums);
  if (keys.length === 0) {
    return null;
  }

  const body = keys.map((key) => emitEnum(key, enums[key].values)).join("\n");
  const contents = `${fileHeader(form.service.namespace)}\n${body}`;

  return {
    name: generatedFileName(applicationKey, "enums"),
    dir,
    contents,
  };
}

function buildDtosFile(form: InvocationForm, applicationKey: string, dir: string): GeneratedFilePayload | null {
  const models = form.service.models ?? {};
  const modelKeys = Object.keys(models);
  if (modelKeys.length === 0) {
    return null;
  }

  const importLines = new Set<string>([
    'import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";',
    'import { Expose } from "class-transformer";',
    'import { IsBoolean, IsNotEmpty, IsNumber, IsOptional, IsString, MinLength } from "class-validator";',
  ]);

  const enumKeys = Object.keys(form.service.enums ?? {});
  if (enumKeys.length > 0) {
    const enumImports = enumKeys.map((k) => enumKeyToClassName(k)).join(", ");
    importLines.add(`import { ${enumImports} } from "${generatedSiblingImport(applicationKey, "enums")}";`);
  }

  const classBlocks: string[] = [];
  for (const modelKey of modelKeys) {
    const { code, imports } = emitModelClass(modelKey, form);
    imports.forEach((line) => importLines.add(line));
    classBlocks.push(code);
  }

  const contents = `${fileHeader(form.service.namespace)}\n${Array.from(importLines).join("\n")}\n\n${classBlocks.join("\n")}`;
  return {
    name: generatedFileName(applicationKey, "dtos"),
    dir,
    contents,
  };
}

export async function generateNestJsDtos(form: InvocationForm): Promise<GeneratedFilePayload[]> {
  const applicationKey = resolveApplicationKey(form.service);
  const dir = generatedDir(applicationKey);
  const files: GeneratedFilePayload[] = [];

  const enumsFile = buildEnumsFile(form, applicationKey, dir);
  if (enumsFile) {
    files.push(enumsFile);
  }

  const dtosFile = buildDtosFile(form, applicationKey, dir);
  if (dtosFile) {
    files.push(dtosFile);
  }

  return files;
}
